### ISSUE TITLE
Fix github action pipeline

### ISSUE THREAD

**Issue by jimmyhalimi** [MassCalculator/masscalculator-core#13]

**Comment by genciberisha** [comment]
Seems good to me, however, take a look at [this](https://github.com/genciberisha/opencv/blob/4.x_with_custom_actions/.github/workflows/sync.yml).

**Comment by jimmyhalimi** [comment]
Looks great. I will do some more strucuring in the organisation as a ehole, and after I finish I will add issues to do the github actions. Definitely could have some help there.

**Comment by genciberisha** [comment]
This looks like a promising project.
Would love to help!
